#!/sbin/openrc-run
# /etc/init.d/bazarr

name="Bazarr"
description="Subtitle manager for Sonarr and Radarr"

directory="${directory:-/var/lib/bazarr}"
command_user="${command_user:-bazarr:bazarr}"

supervisor="supervise-daemon"
pidfile="/run/${RC_SVCNAME}.pid"
command="/usr/bin/bazarr"
command_args="-c ${directory}"
respawn_delay=5
respawn_max=10

depend() {
    need net
    after firewall
}

start_pre() {
    checkpath --directory --mode 0755 --owner "${command_user}" "${directory}"
}



