#!/sbin/openrc-run

name="Bazarr"
description="Subtitle manager for Sonarr and Radarr"
export UNRAR_CMD="${BAZARR_CMD_UNRAR:-}"

command="/usr/bin/bazarr"
command_args="-c ${BAZARR_DATADIR}"
command_user="${BAZARR_USER}:${BAZARR_GROUP}"
pidfile="/run/${RC_SVCNAME}.pid"

depend() {
    need net
    after firewall
}

start_pre() {
    checkpath -d -o "${BAZARR_USER}:${BAZARR_GROUP}" -m 755 "$(dirname ${pidfile})"
    checkpath -d -o "${BAZARR_USER}:${BAZARR_GROUP}" -m 755 "${BAZARR_DATADIR}"
}
